### ISSUE TITLE
initialization  failed

### ISSUE THREAD

**Issue by xiaomage11** [Maratyszcza/NNPACK#101]
enum nnp_status init_status = nnp_initialize();
    if (init_status != nnp_status_success) {
        printf("init failed");
        return 0;
    }
I run the program，initialization do not pass ,it is failed, I want to know what happened for this.

I want to ask  that  does nnpack must run with i7 CPU?

**Comment by edmBernard** [comment]
Do you run NNPACK on server (virtual device) with vCPU ?

**Comment by xiaomage11** [comment]
@edmBernard YES,I run NNPACK on server (virtual device) with vCPU.

**Comment by edmBernard** [comment]
@xiaomage11 Bad luck :-(
The issue comes from the missing L3 cache with vCPU.
You can try this https://github.com/Maratyszcza/NNPACK/issues/33 (I don't test it)

**Comment by Maratyszcza** [comment]
@xiaomage11 Most likely, you vCPU doesn't expose L3 cache. Another possibility is that it doesn't support AVX2 instructions, required to run server version of NNPACK.
