### ISSUE TITLE
Operating environment in raspberry

### ISSUE THREAD

**Issue by xiaomage11** [Maratyszcza/NNPACK#102]
thanks for you ,help me solve many questions, today,I have a question for  Operating environment. when I install NNPACK in raspberry,when go to the last step,(ninja),it is not go pass ,I want to ask,do raspberry can install NNPACK. @Maratyszcza

**Comment by Maratyszcza** [comment]
Raspberry Pi 2 and 3 are supported. Caffe2 includes a script to build Caffe2+NNPACK for Rapsbian [here](https://github.com/caffe2/caffe2/blob/master/scripts/build_raspbian.sh)

**Comment by xiaomage11** [comment]
@Maratyszcza I see your answer, Raspberry Pi 2 and 3 are supported,I want to ask is it install follow the building in readme?

**Comment by Maratyszcza** [comment]
@xiaomage11 Yes, you should be able to build NNPACK for Raspberry Pi 2/3 following the README.

**Comment by danFromTelAviv** [comment]
> Raspberry Pi 2 and 3 are supported. Caffe2 includes a script to build Caffe2+NNPACK for Rapsbian [here](https://github.com/caffe2/caffe2/blob/master/scripts/build_raspbian.sh)

The link is broken I assume you are talking about : 
https://github.com/pytorch/pytorch/blob/master/scripts/build_raspbian.sh
If so I am not sure why NNPACK would be installed in this case??

**Comment by Maratyszcza** [comment]
@danFromTelAviv: Caffe2 build includes NNPACK by default, see https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L124

**Comment by danFromTelAviv** [comment]
thank you for getting back to me so quickly. 

well that makes sense ( face palm ). 

When running the script it did include nnpack by default as promissed. however there were other issues with pybind ://
