### ISSUE TITLE
caffe_nnp_convolution_output<float> not support bigger padd ,that's why ?

### ISSUE THREAD

**Issue by victorygogogo** [Maratyszcza/NNPACK#103]
nnp_status caffe_nnp_convolution_output<float>(
    nnp_convolution_algorithm algorithm,
    size_t batch_size,
    size_t input_channels,
    size_t output_channels,
    nnp_size input_size,
    nnp_padding input_padding,
    nnp_size kernel_size,
    const float input[],
    const float kernel[],
    const float bias[],
    float output[],
    pthreadpool_t threadpool) {
  return nnp_convolution_output(algorithm,
    batch_size, input_channels, output_channels,
    input_size, input_padding,
    kernel_size,
    input, kernel, bias, output,
    threadpool,
    nullptr);
	
if (max(input_padding.top, input_padding.bottom) >= kernel_size.height) {
		return nnp_status_invalid_input_padding;
	}

	if (max(input_padding.left, input_padding.right) >= kernel_size.width) {
		return nnp_status_invalid_input_padding;
	}

**Comment by Maratyszcza** [comment]
Because mathematically, if padding is greater than kernel size, you are padding your output (note: **not** input) with zeroes.

**Comment by victorygogogo** [comment]
FCN  first layer pad is 100 ,so that NNPACK can not run in the first layer. It's a bug of NNPACK.

**Comment by Maratyszcza** [comment]
What is the use-case for padding greater than kernel_size?

**Comment by victorygogogo** [comment]
Fully Convolutional Networks ,the first layer padding is 100.  and a lot of padding is bigger than kernel size too.

**Comment by Maratyszcza** [comment]
Why do you need padding > kernel_size? The extra padding results in pixels of output images initialized to constant values, they don't contain any useful signal. Unless I'm missing something, you could re-train your network without such large padding, and get a faster and similarly accurate model.
