### ISSUE TITLE
NNPACK caffe_nnp_convolution_output using a lot of memory and the speed is not fast.

### ISSUE THREAD

**Issue by victorygogogo** [Maratyszcza/NNPACK#104]
I test it on msm8953.

 NNPACK caffe_nnp_convolution_output is not fast.

is there some switch in NNPACK to speed up ?

I want to use neon.

**Comment by Maratyszcza** [comment]
Why do you use `nnp_convolution_output`? It is optimized for training and large batch size. On mobile use-cases, typical batch size is 1, and `nnp_convolution_inference` handles this case much better.

**Comment by victorygogogo** [comment]
I use nnp_convolution_inference ,it is the same problem.
