### ISSUE TITLE
How to control the number of thread?

### ISSUE THREAD

**Issue by xiaomage11** [Maratyszcza/NNPACK#105]
I want to know how to control the number of thread. where can i find and change the thread? thank you! @Maratyszcza

**Comment by Maratyszcza** [comment]
You specify the desired number of threads when you create a thread pool, see `pthreadpool_create` in [Maratyszcza/pthreadpool](https://github.com/Maratyszcza/pthreadpool). If you pass `NULL` as the thread pool parameter to NNPACK functions, it will run in single-thread mode on the calling thread.
