### ISSUE TITLE
ARMv7 android error

### ISSUE THREAD

**Issue by lxy890123** [Maratyszcza/NNPACK#106]
In my program, I initialized the nnpack with "enum nnp_status init_status = nnp_initialize();", when i builded it and link with "libnnpack.a", i got a lot of link errors as follows, what could be wrong with my lib(libnnpack.a)?
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_fft16x16_with_offset__psimd'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_ifft8x8_with_bias_with_relu__psimd'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_ifft8x8_with_bias__psimd'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_ifft8x8_with_offset__psimd'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_ifft16x16_with_offset__psimd'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_ifft16x16_with_bias__psimd'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_fft8x8_with_offset__psimd'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_owt8x8_3x3_with_bias_with_relu__neon'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_owt8x8_3x3_with_bias__neon'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_owt8x8_3x3__neon'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_kwt8x8_3Rx3R__neon'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_kwt8x8_3x3__neon'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_iwt8x8_3x3_with_offset__neon'
jni/../jni/../src/init.c:681: error: undefined reference to 'nnp_ifft16x16_with_bias_with_relu__psimd

**Comment by Maratyszcza** [comment]
This is strange. I suggest to update sources for NNPACK and its dependencies.

**Comment by lxy890123** [comment]
thanks, I linked the project to "libnnpack.a" and "libnnpack_ukernels.a",  and the problem was solved.

**Comment by lironmo** [comment]
have the same issue, i am using the version: https://github.com/tiny-dnn/NNPACK/

**Comment by lironmo** [comment]
i check and it seems that some symbols in the binaries are undefined:
nm -an /home/liron/work/pixoneye/lod-tiny-dnn/NNPACK/obj/local/armeabi-v7a/objs/fourier-psimd-test/jni/__/test/fourier/psimd.o | grep nnp
         U nnp_fft16_4real__psimd
         U nnp_fft16_dualreal__psimd
         U nnp_fft16_dualreal__ref
         U nnp_fft16_real__ref
         U nnp_fft16_soa__psimd
         U nnp_fft16_soa__ref
         U nnp_fft4_4aos__psimd
         U nnp_fft4_aos__ref
         U nnp_fft8_4aos__psimd
         U nnp_fft8_4real__psimd
         U nnp_fft8_aos__ref
         U nnp_fft8_dualreal__psimd
         U nnp_fft8_dualreal__ref
         U nnp_fft8_real__ref
         U nnp_fft8_soa__psimd
         U nnp_fft8_soa__ref
         U nnp_ifft16_4real__psimd
         U nnp_ifft16_dualreal__psimd
         U nnp_ifft16_dualreal__ref
         U nnp_ifft16_real__ref
         U nnp_ifft16_soa__psimd
         U nnp_ifft16_soa__ref
         U nnp_ifft4_4aos__psimd
         U nnp_ifft4_aos__ref
         U nnp_ifft8_4aos__psimd
         U nnp_ifft8_4real__psimd
         U nnp_ifft8_aos__ref
         U nnp_ifft8_dualreal__psimd
         U nnp_ifft8_dualreal__ref
         U nnp_ifft8_real__ref
         U nnp_ifft8_soa__psimd
         U nnp_ifft8_soa__ref


nm -an /home/liron/work/pixoneye/lod-tiny-dnn/NNPACK/obj/local/armeabi-v7a/libnnpack.a | grep nnp_fft8x8_with_offset__psimd
         U nnp_fft8x8_with_offset__psimd
