### ISSUE TITLE
Armv8 Android compile error

### ISSUE THREAD

**Issue by dzyong** [Maratyszcza/NNPACK#107]
When I compile Armv8 Android version.
It report that float16x4_t hasn't been defined.
It seems that Armv8 neon only define float32x4_t and float32x2_t.

Does anyone know how to fix this?
Thanks.

**Comment by Maratyszcza** [comment]
Are you using the latest Android NDK?

**Comment by dzyong** [comment]
No, I use android-ndk-r12b.

**Comment by Maratyszcza** [comment]
This NDK versions is too old. Please update and try with the r15c.

**Comment by dzyong** [comment]
Thanks so much.
I compile it with r14b successfully.

Is there any guide for how to merge NNPACK into caffe?
I'm following this patch to do this:
https://github.com/ajtulloch/caffe/commit/05151a47824b2ec02e4cb707f06a2996e46ff9c7

**Comment by Maratyszcza** [comment]
@dzyong NNPACK integration with Caffe is no longer maintained. If you want to have something actively supported, try Caffe2 or MXNet.
