### ISSUE TITLE
build fails on ppc64le

### ISSUE THREAD

**Issue by janfrode** [Maratyszcza/NNPACK#114]
I failed to build on ppc64le because of:

~/caffe2-1/third_party/NNPACK$ cmake .
CMake Error at CMakeLists.txt:30 (MESSAGE):
  Unrecognized CMAKE_SYSTEM_PROCESSOR = ppc64le
 
It works if I add ppc64le to line 29 of CMakeLists.txt:

ELSEIF(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(i686|x86_64|armv5te|armv7-a|armv7l|aarch64|ppc64le)$")

**Comment by janfrode** [comment]
But maybe this isn't enough.. I see now that it's failing on some test. i.e.:

$ make test
Running tests...
Test project /home/janfrode/caffe2-1/third_party/NNPACK
      Start  1: convolution-output-smoketest
 1/34 Test  #1: convolution-output-smoketest ............***Failed    6.17 sec
<snip>
[----------] Global test environment tear-down
[==========] 52 tests from 3 test cases ran. (6166 ms total)
[  PASSED  ] 50 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] WT8x8.few_output_channels
[  FAILED  ] WT8x8.few_output_channels_with_relu

and then:

      Start  2: convolution-output-alexnet
 2/34 Test  #2: convolution-output-alexnet ..............***Failed  334.10 sec

[==========] 22 tests from 3 test cases ran. (334097 ms total)
[  PASSED  ] 16 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] WT8x8.conv3
[  FAILED  ] WT8x8.conv3_with_relu
[  FAILED  ] WT8x8.conv4
[  FAILED  ] WT8x8.conv4_with_relu
[  FAILED  ] WT8x8.conv5
[  FAILED  ] WT8x8.conv5_with_relu

I obviously have no idea what I'm doing, so if someone would be interested in guiding me through debugging this, that would be much appreciated.

**Comment by Maratyszcza** [comment]
Try to configure with `-DNNPACK_BACKEND="psimd"`, maybe that helps

**Comment by Maratyszcza** [comment]
Generally, NNPACK on PPC64 is not supported, and some planned future changes will make it impossible to build on PPC64.

**Comment by janfrode** [comment]
Ok, thanks. I'll just disable NNPACK in my caffe2 build then.
