### ISSUE TITLE
Cannot build anymore on Power architecture

### ISSUE THREAD

**Issue by laetitiaoist** [Maratyszcza/NNPACK#115]
CMake Error at third_party/NNPACK/CMakeLists.txt:32 (MESSAGE):
  Unrecognized CMAKE_SYSTEM_PROCESSOR = ppc64le

Since this commit maybe "Support CMake build" 

Can you remove this check or add power architecture?

**Comment by Maratyszcza** [comment]
I do not test on PPC, and don't intend to support it. Right now you can build NNPACK for PPC with small changes in CMakeFiles, but in the near future, NNPACK will add [https://github.com/Maratyszcza/cpuinfo](cpuinfo) as a dependency, and will stop building for Power.
