### ISSUE TITLE
Illegal instruction (core dumped) FAILED: fourier-x86_64-avx2-test

### ISSUE THREAD

**Issue by FCInter** [Maratyszcza/NNPACK#116]
I installed the NNPACK following the instructions in the README, i.e.

```
[sudo] pip install --upgrade git+https://github.com/Maratyszcza/PeachPy
[sudo] pip install --upgrade git+https://github.com/Maratyszcza/confu
git clone https://github.com/Maratyszcza/NNPACK.git
cd NNPACK
confu setup
python ./configure.py
ninja
```
The only difference is that I built the ```ninja``` from source because the version from ```apt-get``` is merely 1.5.1 and it was reported too old when I was testing the test case of NNPACK.

However, I still got error when I tested ```ninja smoketest```, as recommended by the README. The error message are as follows:

```
[0/10] RUN fourier-x86_64-avx2-test
[==========] Running 15 tests from 15 test cases.
[----------] Global test environment set-up.
[----------] 1 test from FFT8_WITHIN_ROWS
[ RUN      ] FFT8_WITHIN_ROWS.match_reference
Illegal instruction (core dumped)
FAILED: fourier-x86_64-avx2-test 
/home/mypath/Downloads/learn/nnpack/NNPACK/bin/fourier-x86_64-avx2-test --gtest_color=yes
ninja: build stopped: subcommand failed.
```

What's wrong with the installation?
I'm using Ubuntu 16.04.1 LTS on my PC.

**Comment by Maratyszcza** [comment]
Maybe your processor doesn't support AVX2?

**Comment by FCInter** [comment]
Sorry I don't know what is AVX2. Could you please tell me how to fix it? Maybe I should install something called AVX2?
Thank you.

**Comment by Maratyszcza** [comment]
AVX2 is a set of processor instructions supported by Intel Haswell/Broadware/Skylake and AMD Ryzen. If your processor doesn't support these instructions, there is no workaround.

**Comment by rsaxvc** [comment]
If anyone gets here just trying to get NNPACK to run, but not worried about the specific instruction set in use, you can build using the psimd target like so:

`python ./configure.py --backend psimd`
