### ISSUE TITLE
convolution-benchmark  core dumped if output-subsampling isn't 1x1

### ISSUE THREAD

**Issue by wangshankun** [Maratyszcza/NNPACK#125]
bin/convolution-benchmark -ic 3 -is 231 231 -ks 11 11 -oc 96 **--output-subsampling 4 4**
Batch size: 1
Input channels: 3
Output channels: 96
Input: 231x231 with implicit padding 0
Kernel: 11x11
Subsampling: 4x4
Algorithm: auto
Threads: 8
Iterations: 3
Segmentation fault (core dumped)

**Comment by Maratyszcza** [comment]
By default, `convolution-benchmark` is running in `output` mode, i.e. calls `nnp_convolution_output` which does not support convolution with strides. Only the inference function `nnp_convolution_inference` currently supports strides. You can switch to inference mode using `-m inference`
