### ISSUE TITLE
When I use NNPACK in darknet, the net's output is incorrect.

### ISSUE THREAD

**Issue by yjcn** [Maratyszcza/NNPACK#128]
I use https://github.com/digitalbrain79/darknet-nnpack , When the NNPACK is enabled, the net's out put is incorrect. And with same code, when i disable NNPACK, the output is correct.

**Comment by Maratyszcza** [comment]
This looks like **darknet-nnpack** issue. Unless you report which NNPACK function produces wrong result, I can't even investigate it.
