### ISSUE TITLE
Feature request: set download dependency root directory

### ISSUE THREAD

**Issue by dabraude** [Maratyszcza/NNPACK#131]
Would it be possible to set the download directory instead of always being `${CMAKE_BINARY_DIR}/*-download`

to something like `${CONFU_DEPENDENCIES_SOURCE_DIR}/*-download` don't mind doing it myself if you are happy with that name and `CONFU_DEPENDENCIES_SOURCE_DIR` defaults to `CMAKE_BINARY_DIR`

**Comment by Maratyszcza** [comment]
Did you try to set `CONFU_DEPENDENCIES_BINARY_DIR`? IIUC, the default download directory is `CONFU_DEPENDENCIES_BINARY_DIR/project-name` where project name is from `cmake/*.cmake`

**Comment by Maratyszcza** [comment]
Correction: the actual download directory is `${CONFU_DEPENDENCIES_SOURCE_DIR}/dependency-name`. `${CMAKE_BINARY_DIR}/*-download` is a build directory for a CMake project that downloads the dependency.

**Comment by dabraude** [comment]
Ok is that download project directory necessary after the project has built for the first time? If not the Cmake for MXNet can delete it, otherwise I aiming to put those `*-download` directories under `${CMAKE_BINARY_DIR}/3rdparty/NNPack/dep/*-download`

**Comment by Maratyszcza** [comment]
It is not necessary, but I think CMake with download dependencies again if it doesn't find expected files in `*-download` directories

**Comment by Maratyszcza** [comment]
Would it work for you if `*-download` files will be in `${CONFU_DEPENDENCIES_BINARY_DIR}/*-download` instead of `${CMAKE_BINARY_DIR}/*-download`?

**Comment by dabraude** [comment]
Yeah that would be perfect

**Comment by Maratyszcza** [comment]
Ok, I will move on with this change. It will take a while as I have to update all NNPACK dependencies.

**Comment by Maratyszcza** [comment]
Shipped in 04d045a2efe3785edcd7ccc72c2e81dc7a3377c3

**Comment by dabraude** [comment]
awesome thanks.
