### ISSUE TITLE
Build requires -std=gnu++11 but specifies -std=c++11

### ISSUE THREAD

**Issue by byron-hawkins** [Maratyszcza/NNPACK#133]
Following the build instructions results in errors about the numerical constant suffixes `p` and `f`, which require compiler flag `-std=gnu++11`. The build specifies `-std=c++11`. For some reason it does not work to change the `CMakeLists.txt` files--it continues to specify `-std=c++11`, even after deleting the build directory and regenerating `build.ninja`. So I hacked `build.ninja` directly and it builds fine now. 

    Linux localhost.localdomain 4.13.16-100.fc25.x86_64 #1 SMP Mon Nov 27 19:52:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    gcc (GCC) 6.4.1 20170727 (Red Hat 6.4.1-1)

**Comment by Maratyszcza** [comment]
Fixed in 6d76eedcc2be58333782b6a6f520e8dfa05d445c
