### ISSUE TITLE
NNPack+MXNet Build Fails on Raspberry Pi 3

### ISSUE THREAD

**Issue by nextseto** [Maratyszcza/NNPACK#135]
Hello! I am attempting to install NNPack on my Raspberry Pi so I can accelerate my machine learning applications with MXNet 1.0. For this installation, I installed a clean version of the latest Raspbian OS (Stretch with Desktop, Kernel 4.9).

However, when I try to build NNPack together with MXNet it fails and I receive this error.

```
/home/pi/NNPACK/lib//libnnpack.a(init.c.o): In function `init_hwinfo':
/home/pi/NNPACK/src/init.c:426: undefined reference to `cpuinfo_isa'
/home/pi/NNPACK/lib//libnnpack.a(init.c.o): In function `nnp_initialize':
/home/pi/NNPACK/src/init.c:574: undefined reference to `cpuinfo_initialize'
/home/pi/NNPACK/lib//libnnpack.a(init.c.o): In function `nnp_deinitialize':
/home/pi/NNPACK/src/init.c:584: undefined reference to `cpuinfo_deinitialize'
collect2: error: ld returned 1 exit status
Makefile:421: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1
```

After trying the instructions in the READMEs in this repository, I looked at other instructions found [here](https://aws.amazon.com/blogs/machine-learning/speeding-up-apache-mxnet-using-the-nnpack-library/) and [here](https://medium.com/@julsimon/speeding-up-apache-mxnet-with-the-nnpack-library-raspberry-pi-edition-e444b446a180). However, all have led to the same error.

Am I doing something wrong, or does NNPack only support a certain build of MXNet?

Thanks!

**Comment by Maratyszcza** [comment]
NNPACK's migrated to CMake as the primary build system, and MXNet's adaptation to this change it still work-in-progress, see apache/incubator-mxnet#9860 and cc @dabraude and @tqchen.

The error you see arises from not linking [cpuinfo](https://github.com/Maratyszcza/cpuinfo) library, used in NNPACK to detect ISA features and cache sizes.

**Comment by Maratyszcza** [comment]
@nextseto Alternatively, you may try Caffe2, which integrates the latest NNPACK.

**Comment by nextseto** [comment]
@Maratyszcza Hi, thank you for the explanation. 

Since NNPack + MXNet was successfully installed in previous [tutorials](https://medium.com/@julsimon/speeding-up-apache-mxnet-with-the-nnpack-library-raspberry-pi-edition-e444b446a180), what version of NNPack and MXNet would still work together?

**Comment by Maratyszcza** [comment]
Probably, but if you want a version that doesn't depend on cpuinfo, you'd have to go to a very old NNPACK revision. f824d521126fea15d01cb1da5cb9dab94602b525 is the last that didn't depend on cpuinfo

**Comment by dabraude** [comment]
It wouldn't work even with an older version of nnpack as there was a rewrite of the operators, I haven't had a lot of time lately to work on it but hopefully next week I can.

**Comment by nextseto** [comment]
Thanks @dabraude!
As a stopgap solution, MXNet 0.11 and NNPack [3627062](https://github.com/Maratyszcza/NNPACK/commit/3627062907e01ba5f030730f1027dd773323e0e3) does still build.

**Comment by juliensimon** [comment]
Hello @nextseto, I'm the author of the two posts you mentioned ;)

I ran into the same issue, this is how you can built MXNet 1.1.0 with the latest NNPACK and cpuinfo libs. Using this build, I was able to successfully predict images with a pre-trained version of Inception v3.

1) Build NNPACK as explained

2) Build cpuinfo in a similar fashion
git clone https://github.com/Maratyszcza/cpuinfo.git
cd cpuinfo
add -fPIC to cflags and cxxflags in build.ninja
build cpuinfo: confu setup && python ./configure.py && ninja

3) Add these to the MXNet makefile (with your own directories, of course):
NNPACK = /home/pi/dev/NNPACK
CPUINFO = /home/pi/dev/cpuinfo
ADD_LDFLAGS = -L$(NNPACK)/lib/ -lnnpack -lpthreadpool -L$(CPUINFO)/lib/ -lcpuinfo
ADD_CFLAGS = -I$(NNPACK)/include/ -I$(NNPACK)/deps/pthreadpool/include/

4) Build and install MXNet.

I hope this helps... and I guess I need an updated version of my post!

Cheers to @Maratyszcza for building such great tools.
