### ISSUE TITLE
Feature request: broader winograd 3x3 convolution stride 2 support

### ISSUE THREAD

**Issue by zeno40** [Maratyszcza/NNPACK#137]
Hi,

I noticed in the sources winograd 3x3 stride 2 convolution support for neon cpu.
As this is a very widely used layer are there plans to make this also work on non neon cpu's (intel/amd)?
Would be a very useful addition and great speed-up.

Thanks

**Comment by Maratyszcza** [comment]
3x3 stride 2 Winograd for NEON wasn't much of a win, so no plans to port it to other platforms.

**Comment by lironmo** [comment]
@Maratyszcza,  Thank you very much for taking the time to answer.
We are planning to develop  strided convolution for training, in order to support training.

we wondered why  "3x3 stride 2 Winograd for NEON wasn't much of a win", compare to what ?

**Comment by victorygogogo** [comment]
@lironmo  hello how about your stride2 winograd convolution ?can you share some infomation about it?
