### ISSUE TITLE
Benchmarking Error in NNPACK

### ISSUE THREAD

**Issue by charlyng** [Maratyszcza/NNPACK#14]
I have set up a new environment as follows:
Ubuntu 12.04 + Intel Core i7-3770

I entered the following codes as shown in #3 for benchmarking.
> bin/convolution-benchmark --mode output --batch 128 --input-channels 1024 --output-channels 1024 --input-size 40 40 --kernel-size 5 5 --input-padding 2 --algorithm ft16x16

But I encountered an error as shown:
> ~/Programs/NNPACK$ ./benchmark.py -l fully-connected -m inference -n vgg-a
> NNPACK initialization failed: error code 51
> Traceback (most recent call last):
> File "./benchmark.py", line 184, in <module>
>    print("{name}\t{measurements}".format(name=name, measurements="\t".join(measurements)))
> TypeError

May I know how to solve this error?

Thank you.

**Comment by Maratyszcza** [comment]
Core i7-3770 is based on Ivy Bridge architecture, and it doesn't support AVX2 instructions. Thus the "NNPACK initialization failed" error.

**Comment by nicolasvasilache** [comment]
It seems you are getting this question quite a lot.
How about failing harder with an explicit error message based on, say cat /proc/cpuinfo, by default with an option the user can pass to cross-compile ?

**Comment by Maratyszcza** [comment]
It is an explicit error code. Error code 51 == `nnp_status_unsupported_hardware`

**Comment by charlyng** [comment]
@Maratyszcza @nicolasvasilache 

Thank you for your help.
