### ISSUE TITLE
smoketest fails in convolution-inference

### ISSUE THREAD

**Issue by zeno40** [Maratyszcza/NNPACK#142]
I just did a fresh compile of NNPACK because in my ported build I encountered a failure in the smoketest. But the same thing is happening in NNPACK.

[6/10] RUN convolution-inference-smoketest
[==========] Running 132 tests from 9 test cases.
[----------] Global test environment set-up.
[----------] 16 tests from FT8x8
[ RUN      ] FT8x8.single_tile
Floating point exception (core dumped)
FAILED: convolution-inference-smoketest
/home/Filip/NNPACK/bin/convolution-inference-smoketest --gtest_color=yes
ninja: build stopped: subcommand failed.

thanks

**Comment by Maratyszcza** [comment]
I tried it just now, and couldn't reproduce it. Could you post which platform you build on, and a complete sequence of commands you run during the build?

**Comment by zeno40** [comment]
I'm on a fresh install of Ubuntu 18.04.
gcc 7.3
clang 6.0.0

**Comment by zeno40** [comment]
Thanks, the issue is gone when using clang.
