### ISSUE TITLE
Missing installation of libclog.a

### ISSUE THREAD

**Issue by ayounes-nviso** [Maratyszcza/NNPACK#143]
Hello,

With latest commit, when compiled statically, libclog is not installed. Adding this smippet at the end of "src/deps/cpuinfo/deps/clog/CMakeLists.txt" fixes the issue.

INSTALL(TARGETS clog
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})

**Comment by Maratyszcza** [comment]
Fixed in pytorch/cpuinfo@83f61bb03a32f3276bec3af6a4c6a6ae861c78f2

**Comment by ayounes-nviso** [comment]
Dear Marat,

Thanks for fixing this. 

I have a suggestion to avoid this kind of issue in the future. Why don't you switch to git submodules instead of cloning at cmake time? This way you can make sure that the top repo has always a compilable state.

I can provide a patch for that if you want...

Thanks again for your support and for NNPACK,
Abdel

**Comment by ayounes-nviso** [comment]
As NNPACK and most of its dependencies are already submodules of Pytorch, my suggestion above is not a good idea so please forget about it!
We will add the dependencies by ourselves and set the XXX_SOURCE_DIR as you are suggesting. Thanks.
