### ISSUE TITLE
confu setup failed

### ISSUE THREAD

**Issue by zeno40** [Maratyszcza/NNPACK#145]
after doing

git clone https://github.com/Maratyszcza/NNPACK.git
cd NNPACK

confu setup
Fetch dependency pthreadpool from https://github.com/Maratyszcza/pthreadpool.git
Fetch dependency pthreadpool:fxdiv from https://github.com/Maratyszcza/FXdiv.git
Setup dependency pthreadpool:fxdiv:googletest using built-in recipe confu.recipes.pthreadpool:fxdiv:googletest
Setup dependency pthreadpool:fxdiv:googlebenchmark using built-in recipe confu.recipes.pthreadpool:fxdiv:googlebenchmark
Reuse dependency pthreadpool:googletest from /home/filip/NNPACK/deps/googletest
Reuse dependency pthreadpool:googlebenchmark from /home/filip/NNPACK/deps/googlebenchmark
Fetch dependency cpuinfo from https://github.com/pytorch/cpuinfo.git
Reuse dependency cpuinfo:googletest from /home/filip/NNPACK/deps/googletest
Reuse dependency cpuinfo:googlebenchmark from /home/filip/NNPACK/deps/googlebenchmark
Fatal error: no source provided for dependency clog (cpuinfo:clog)
Fatal error: failed to read project manifest /home/filip/NNPACK/deps/clog/confu.yaml:
Traceback (most recent call last):
  File "/usr/local/bin/confu", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/confu/__main__.py", line 84, in main
    options.process(options, unparsed_args)
  File "/usr/local/lib/python2.7/dist-packages/confu/__main__.py", line 70, in setup_deps
    setup_project_deps(root_dir, root_dir)
  File "/usr/local/lib/python2.7/dist-packages/confu/__main__.py", line 65, in setup_project_deps
    namespace=dep.name if not namespace else namespace + ":" + dep.name)
  File "/usr/local/lib/python2.7/dist-packages/confu/__main__.py", line 65, in setup_project_deps
    namespace=dep.name if not namespace else namespace + ":" + dep.name)
  File "/usr/local/lib/python2.7/dist-packages/confu/__main__.py", line 34, in setup_project_deps
    project = confu.manifest.Project.from_root(project_dir)
  File "/usr/local/lib/python2.7/dist-packages/confu/manifest.py", line 29, in from_root
    with open(manifest_path) as manifest_file:
IOError: [Errno 2] No such file or directory: '/home/filip/NNPACK/deps/clog/confu.yaml'
filip@DESKTOP-GFF13AV:~/NNPACK$ cd deps
filip@DESKTOP-GFF13AV:~/NNPACK/deps$ cd clog
-bash: cd: clog: No such file or directory
filip@DESKTOP-GFF13AV:~/NNPACK/deps$ ls -a
.  ..  cpuinfo  fxdiv  googlebenchmark  googletest  pthreadpool

the clog sources are provided in the /home/filip/NNPACK/deps/cpuinfo/deps/clog directory instead of
/home/filip/NNPACK/deps/clog/ as used above.

thanks

**Comment by Maratyszcza** [comment]
You need to update `confu`

**Comment by zeno40** [comment]
Thanks, the issue is resolved.
