### ISSUE TITLE
Bug in nnp_convolution_kernel_gradient with non-square image/kernel

### ISSUE THREAD

**Issue by Maratyszcza** [Maratyszcza/NNPACK#15]
@szagoruyko found that `nnp_convolution_kernel_gradient` does not match Torch results when image and/or kernel is non-square (i.e. `width != height`). Probably it is also related to Caffe backprop mismatch noticed by @ajtulloch. @szagoruyko checked that the reference implementation `nnp_convolution_kernel_gradient__reference` from `nnpack/reference.h` does not have this bug. TODO:

- Add test cases for non-square images and kernels (currently all NNPACK tests cases for convolution use square images and kernels).
- Fix the bug

**Comment by ajtulloch** [comment]
Awesome, I'll update the Caffe backprop stuff when this is in.

**Comment by Maratyszcza** [comment]
Test cases shipped in ce59c9cadd2d561c765953dbfce1ac9bfa557099
