### ISSUE TITLE
NNPack is not supported here!

### ISSUE THREAD

**Issue by bendidi** [Maratyszcza/NNPACK#150]
Hello, 

I'm trying to run a caffe2 model in lambda , but I get the following error : 

`Error in cpuinfo: failed to parse the list of possible procesors in /sys/devices/system/cpu/possible 
Error in cpuinfo: failed to parse the list of present procesors in /sys/devices/system/cpu/present 
RuntimeError: [enforce fail at conv_op.cc:24] nnpack_status == nnp_status_success. NNPack is not supported here!Error from operator: 
input: "data" input: "conv1_w" input: "res_conv1_bn_b" output: "conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 2 } device_option
{}
engine: "NNPACK"`

I'm building caffe2 using the following cmake config : 

`cmake -DUSE_GFLAGS=OFF \
          -DUSE_GLOG=OFF \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_INSTALL_PREFIX="/cf2/" \
          -DCMAKE_PREFIX_PATH="/cf2/" \
          -DUSE_GLOO=OFF \
          -DUSE_CUDA=OFF \
          -DUSE_MPI=OFF \
          -DUSE_METAL=OFF \
          -DUSE_NCCL=OFF \
          -DUSE_MOBILE_OPENGL=OFF \
          -DBUILD_CUSTOM_PROTOBUF=OFF \
          -DUSE_LEVELDB=OFF \
          -DUSE_LMDB=OFF \
          -DUSE_NUMA=OFF \
          -DUSE_OPENCV=OFF \
          -DUSE_NCCL=OFF \
          ..`

thanks !

**Comment by Maratyszcza** [comment]
The error originated not in NNPACK, but in [cpuinfo](https://github.com/pytorch/cpuinfo) library. Apparently, the files `/sys/devices/system/cpu/present` and `/sys/devices/system/cpu/possible` are not available on this system, which is unusual. Could you post a dump of `/sys/devices/system/cpu/` tree on this system?

**Comment by Maratyszcza** [comment]
Is `sysfs` mounted on this system?

**Comment by Maratyszcza** [comment]
I see that both `/sys/devices/system/cpu/present` and `/sys/devices/system/cpu/possible` files exist. @VisionZQ: could you dump the contents of these files?

**Comment by VisionZQ** [comment]
Hi, 
I have check the  **Platforms and requirements** table again.
**3-level cache hierarchy** exist in my PC.
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Model name:            Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
Stepping:              9
CPU MHz:               3399.875
CPU max MHz:           3600.0000
CPU min MHz:           1600.0000
BogoMIPS:              6385.67
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3

But,
AVX2 is not support to CPU!!!!! so, this is is right reason caused the issue?
`
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts flush_l1d

`

**Comment by Maratyszcza** [comment]
yes, NNPACK on x86-64 requires AVX2
