### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by XDongiang** [Maratyszcza/NNPACK#159]
[root@hepserver build]# cmake -G Ninja -D BUILD_SHARED_LIBS=ON ..
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by Maratyszcza** [comment]
You need to install [Ninja](https://ninja-build.org/)

**Comment by XDongiang** [comment]
[root@hepserver build]# cmake -G Ninja -D BUILD_SHARED_LIBS=ON ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- Downloading six (Python package) to /home/dx/NNPACK/deps/six (define PYTHON_SIX_SOURCE_DIR to avoid it)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dx/NNPACK/build/deps/six-download
[1/9] Creating directories for 'six'
[2/9] Performing download step (download, verify and extract) for 'six'
FAILED: six-prefix/src/six-stamp/six-download 
cd /home/dx/NNPACK/deps && /usr/local/bin/cmake -P /home/dx/NNPACK/build/deps/six-download/six-prefix/src/six-stamp/download-six.cmake && /usr/local/bin/cmake -P /home/dx/NNPACK/build/deps/six-download/six-prefix/src/six-stamp/verify-six.cmake && /usr/local/bin/cmake -P /home/dx/NNPACK/build/deps/six-download/six-prefix/src/six-stamp/extract-six.cmake && /usr/local/bin/cmake -E touch /home/dx/NNPACK/build/deps/six-download/six-prefix/src/six-stamp/six-download
-- Downloading...
   dst='/home/dx/NNPACK/build/deps/six-download/six-prefix/src/six-1.11.0.tar.gz'
   timeout='none'
-- Using src='https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz'
-- Retrying...
-- Using src='https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz'
CMake Error at /home/dx/NNPACK/build/deps/six-download/six-prefix/src/six-stamp/download-six.cmake:157 (message):
  Each download failed!

    error: downloading 'https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

> You need to install [Ninja](https://ninja-build.org/)

after install ninja , have this error

**Comment by Maratyszcza** [comment]
It seems that libcurl on your system is built without https support. As a work-around, you can download required packages manually, unpack the archives, and set variables e.g. `-DPYTHON_SIX_SOURCE_DIR=/path/to/unpacked/six/package` to make NNPACK use them from the specified directories instead of downloading.

**Comment by RuABraun** [comment]
> You need to install [Ninja](https://ninja-build.org/)

This error still happens when one has Ninja installed.
