### ISSUE TITLE
Is the fully connected layer faster than using the OpenBLAS equivalent?

### ISSUE THREAD

**Issue by RuABraun** [Maratyszcza/NNPACK#168]

**Comment by RuABraun** [comment]
No it's slower unfortunately.

**Comment by Maratyszcza** [comment]
Thank you for reporting this. Fixed in a344d23816542a1c91bc99c238fa520ac4936f9a

**Comment by Maratyszcza** [comment]
I suggest you take a look at [XNNPACK](https://github.com/google/XNNPACK) library, which is a successor to NNPACK.

**Comment by RuABraun** [comment]
Oh nice! Great I'll try it out. :)
