### ISSUE TITLE
Strides support for convolutional layers

### ISSUE THREAD

**Issue by joker512** [Maratyszcza/NNPACK#17]
Hello, and thank you for your work!

You wrote that **only convolutional layers without stride are supported and pooling size is restricted by 2x2**. But I saw that you've added custom pooling size support recently. Are you going to get rid of stride restriction either? I could help you with the problem if it is possible.

**Comment by Maratyszcza** [comment]
Arbitrary pooling size & stride is already supported.

Convolutional layers with stride will be supported when `im2col+sgemm` lands. Using FFT for strided convolution would decrease the effective kernel size to `kernel.size / kernel.stride`, which in practical architectures is about 2. When kernel size is this small, FFT doesn't offer much algorithmic speedup.

**Comment by joker512** [comment]
Thanks!

**Comment by Maratyszcza** [comment]
Implicit GEMM algorithm and strided convolution is not supported for inference

**Comment by lironmo** [comment]
any plan  to support the feature for training?

**Comment by Maratyszcza** [comment]
@lironmo: no, training in general is low-priority, and no plans to expose strided convolutions in trainingg
