### ISSUE TITLE
convolution-input-gradient-overfeat-test failed on arm64

### ISSUE THREAD

**Issue by Danliran** [Maratyszcza/NNPACK#186]
convolution-input-gradient-overfeat-test  failed on arm64

TEST(FT16x16, conv2) {
	OverFeat_Fast::conv2()
		.batchSize(128)
		.errorLimit(1.0e-5)
		.testInputGradient(nnp_convolution_algorithm_ft16x16);
}

[----------] 4 tests from FT16x16
[ RUN      ] FT16x16.conv2
/home/taishan/master/NNPACK/test/testers/convolution.h:316: Failure
Expected: (median(maxErrors)) < (errorLimit()), actual: 1.11966e-05 vs 1e-05
[  FAILED  ] FT16x16.conv2 (10959 ms)
[ RUN      ] FT16x16.conv3
[       OK ] FT16x16.conv3 (10753 ms)
[ RUN      ] FT16x16.conv4

**Comment by Danliran** [comment]
@Maratyszcza could you please help to investigate this issue?

**Comment by Maratyszcza** [comment]
The error is just above the limit, looks like the error tolerance is just too low in the test
