### ISSUE TITLE
 'vdotq_lane_s32' is invalid in C99 [-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by Chinneil** [Maratyszcza/NNPACK#200]
[ 10%] Building C object _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/src/qs8-igemm/gen/6x8c4-minmax-neondot.c.o
/home/chendongmin/project/tensorflow_lite_cmake/dtln_aec_android_build/xnnpack/src/qs8-gemm/gen/1x16c4-minmax-neondot.c:64:20: warning: implicit declaration of function
      'vdotq_lane_s32' is invalid in C99 [-Wimplicit-function-declaration]
      vacc0x0123 = vdotq_lane_s32(vacc0x0123, vb0123x0123, va0x01234567, 0);
                   ^
/home/chendongmin/project/tensorflow_lite_cmake/dtln_aec_android_build/xnnpack/src/qs8-gemm/gen/1x16c4-minmax-neondot.c:64:18: error: assigning to 'int32x4_t'
      (vector of 4 'int32_t' values) from incompatible type 'int'
      vacc0x0123 = vdotq_lane_s32(vacc0x0123, vb0123x0123, va0x01234567, 0);

**Comment by Maratyszcza** [comment]
The issue is related to XNNPACK, not NNPACK.
