### ISSUE TITLE
NNPACK builds are not bit-for-bit reproducible

### ISSUE THREAD

**Issue by civodul** [Maratyszcza/NNPACK#206]
NNPACK builds are not [bit-for-bit reproducible](https://reproducible-builds.org/docs/definition/) as of commit c07e3a0400713d546e0dea2d5466dd22ea389c73.

As [initially reported](https://issues.guix.gnu.org/50672), investigation suggests that the source of non-determinism has to do with code generated by files such as `src/x86_64-fma/2d-fourier-8x8.py` using PeachPy: the order of symbols such as `nnp_fft8x8_with_offset_and_stream__avx2.__local0` differs between the two different `libnnpack.so` builds (the original report has more details).

Any ideas how to address this?

**Comment by Maratyszcza** [comment]
See Maratyszcza/PeachPy#88
