### ISSUE TITLE
Convolution-inference running slower on newer ARM chipsets

### ISSUE THREAD

**Issue by vpatilvasu** [Maratyszcza/NNPACK#28]
Hi, @Maratyszcza

I ran convolution-inference on some of the Android devices with Qualcomm Snapdragon chipsets and I noticed it's much faster on older chipsets than the newer ones.

NNPACK libraries were compiled with Android-23 for armeabi-v7a ABI.

Following are the input parameters to convolution-inference:
Batch size: 1
Input channels: 16
Output channels: 16
Input: 800x600 with implicit padding 2
Kernel: 5x5
Subsampling: 1x1
Algorithm: FT16x16
Threads: 4
Iterations: 1

**Performance on Snapdragon 805 (older chipset):**
**Time: 227.654 ms**
Input transform: 36.907 ms (16.2%) [2.3 GB/s]
Kernel transform: 0.362 ms (0.2%) [0.8 GB/s]
Output transform: 22.522 ms (9.9%) [3.8 GB/s]
Block multiplication: 60.708 ms (26.7%) [14.5 GFLOPS]
Overhead: 107.156 ms (47.1%)

**Performance on Snapdragon 820 (latest chipset):**
**Time: 349.370 ms**
Input transform: 27.081 ms (7.8%) [3.2 GB/s]
Kernel transform: 0.446 ms (0.1%) [0.6 GB/s]
Output transform: 16.603 ms (4.8%) [5.2 GB/s]
Block multiplication: 41.086 ms (11.8%) [21.4 GFLOPS]
Overhead: 264.154 ms (75.6%)

I'm mainly interested in convolution and the results on 805 look promising. I was hoping to get much better performance on 820.
Is there anything that I can try/tweak to get better performance on 820?

Best Regards.

**Comment by Maratyszcza** [comment]
It looks very strange, because the majority of time is overhead (and its the only part that slowed down). Overhead is mostly the time to allocate and release scratch memory. One way to reduce it is to revise the interface to provide scratch memory allocated externally.

**Comment by vpatilvasu** [comment]
Thanks for the tip. I will look in to the code and try to make this change and report back with my findings.

**Comment by vpatilvasu** [comment]
By explicitly allocating memory outside, following is the performance on 820:

**Time: 84.947 ms**
Input transform: 25.868 ms (30.5%) [3.3 GB/s]
Kernel transform: 0.279 ms (0.3%) [1.0 GB/s]
Output transform: 16.611 ms (19.6%) [5.2 GB/s]
Block multiplication: 42.177 ms (49.7%) [20.8 GFLOPS]
Overhead: 0.011 ms (0.0%)

This is much better and best I've seen till now.Thank you very much for your quick support.
