### ISSUE TITLE
Question on Benchmarks

### ISSUE THREAD

**Issue by aurotripathy** [Maratyszcza/NNPACK#29]
Thank you for this much-needed project. 

The benchmark-related question I have is, 

Do we have to sum up each column below to arrive at the input-to-output inference-path performance number? 

What about the FC and Softmax layer perf numbers?

It looks like these perf-numbers are for individual convolutional layers _only_?

```
VGG-A:conv1         255 ms	303 ms	260 ms	404 ms
VGG-A:conv2	       902 ms	369 ms	267 ms	372 ms
VGG-A:conv3.1      566 ms	308 ms	185 ms	279 ms
VGG-A:conv3.2     1091 ms	517 ms	309 ms	463 ms
VGG-A:conv4.1      432 ms	228 ms	149 ms	188 ms
VGG-A:conv4.2     842 ms	402 ms	264 ms	329 ms
VGG-A:conv5	       292 ms	141 ms	83 ms	114 ms
```

**Comment by Maratyszcza** [comment]
To get inference time for the whole network, you should run the whole network through NNPACK via Torch or Caffe bindings ;) The per-layer benchmarks flush the cache after each iteration, so they would normally overestimate the time it takes to process a layer.
