### ISSUE TITLE
NNPACK build error

### ISSUE THREAD

**Issue by kaishijeng** [Maratyszcza/NNPACK#3]
After python configure.py, I got the following error with  ninja

ninja: error: build.ninja:271: unknown pool name

DO you know why?

**Comment by nicolasvasilache** [comment]
This is likely related to an older ninja version (pre 1.4.0 I think).
Try using the latest: https://ninja-build.org/, it worked for me.

**Comment by kaishijeng** [comment]
It works with the latest ninja.

Thanks

**Comment by kaishijeng** [comment]
How do I run benchmark after compile test since it is not mentioned in the
README?

On Fri, Mar 25, 2016 at 8:07 AM, Nicolas Vasilache <notifications@github.com

**Comment by Maratyszcza** [comment]
There are three ways to benchmark NNPACK:

1. Run `bin/convolution-benchmark`, `bin/fully-connected-benchmark`, or `bin/pooling-benchmark` benchmarks to benchmark layers with arbitrary parameters. E.g.
```bash
bin/convolution-benchmark --mode output --batch 128 --input-channels 1024 --output-channels 1024 --input-size 40 40 --kernel-size 5 5 --input-padding 2 --algorithm ft16x16
```

2. Run `./benchmark.py` script to benchmark layers of AlexNet, OverFeat-Fast, or VGG-A models. E.g.
```bash
./benchmark.py -l fully-connected -m inference -n vgg-a
```

3. Build [Caffe-NNPACK](https://github.com/Maratyszcza/caffe-nnpack) and use [CPU branch of convnet-benchmarks](https://github.com/soumith/convnet-benchmarks/tree/cpu) to benchmark NNPACK integrated into Caffe. You'd need to modify models' prototxt files to add `engine: NNPACK` inside `convolution_param` of the convolutional layers.

**Comment by kaishijeng** [comment]
Seem something is wrong when I tried

bin/convolution-benchmark --mode output --batch 128 --input-channels 1024
--output-channels 1024 --input-size 40 40 --kernel-size 5 5 --input-padding
2 --algorithm ft16x16

It gives the following error:

NNPACK initialization failed: error code 51

**Comment by Maratyszcza** [comment]
This error code means you are not running on a compatible hardware. NNPACK requires a processor with AVX2, i.e. Intel Haswell, Broadwell, or Skylake. It also checks that the processor has L1, L2, and L3 cache, but AFAIK also current Haswell/Broadwell/Skylake SKUs have it.

**Comment by kaishijeng** [comment]
Thanks
