### ISSUE TITLE
Benchmark convolution vs other libraries

### ISSUE THREAD

**Issue by bhack** [Maratyszcza/NNPACK#30]
Have you benchmarked NNPACK convolution over Intel HPC https://github.com/hfp/libxsmm/?

**Comment by Maratyszcza** [comment]
No, but I should. Same for other libraries with overlapping functionality:

- DNN primitives from MKL 2017
- [Open-source MKL-DNN](https://github.com/01org/mkl-dnn)
- DNN primitives in [libxsmm](https://github.com/hfp/libxsmm.git)
- [Qualcomm Snapdragon Math Libraries (QSML)](https://developer.qualcomm.com/software/snapdragon-math-libraries)
- Apple's [BNNS](https://developer.apple.com/reference/accelerate/1912851-bnns)
- Eigen's [TensorConvolution](https://eigen.tuxfamily.org/dox-devel/unsupported/TensorConvolution_8h_source.html)

**Comment by Maratyszcza** [comment]
@alheinecke Could you please clarify the relationship between libxmm, OSS MKL-DNN and closed-source DNN in MKL 2017? Do they use the same implementation?

**Comment by hfp** [comment]
Perhaps of interest: https://software.intel.com/en-us/articles/intel-xeon-phi-delivers-competitive-performance-for-deep-learning-and-getting-better-fast (mentions Intel MKL-DNN as well as LIBXSMM).

**Comment by hfp** [comment]
To support this effort, [LIBXSMM 1.5](https://github.com/hfp/libxsmm/releases/tag/1.5) brought some [benchmark scripts alongside of our sample code](https://github.com/hfp/libxsmm/tree/master/samples/dnn).

**Comment by cancan101** [comment]
I cross posted this on the Eigen issue tracker: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1418.
