### ISSUE TITLE
Problems occur after setting distribution from -1.0 to 1.0

### ISSUE THREAD

**Issue by Jokeren** [Maratyszcza/NNPACK#32]
@Maratyszcza 

To begin with, I checked out the latest commit without any modification. Then, I changed the the distribution in `convolution.h` from the default (0.0, 1.0) to (-1.0, 1.0). It turns out that all tests cannot pass.

Because I would like to test the relu combination, the distribution should be set to contain negative values, just as what you did in the relu tests.

Could we change the `errorLimit` or the evaluation function?

Thanks very much!

**Comment by Maratyszcza** [comment]
@Jokeren distribution with mean zero is particularly problematic because the accumulated result also has a zero mean. I suggest to use uniform distribution on (-0.5, 1.0) or normal distribution with mean 0.25 and stdef 1. If needed, also adjust the `errorLimit`.
