### ISSUE TITLE
Build for Linux/ARMv7

### ISSUE THREAD

**Issue by dprylipko** [Maratyszcza/NNPACK#35]
Hi,
I am wondering whether it is possible to use NNPACK on an ARM device running Ubuntu.
What I understand from requirements, it cannot be built natively, but is cross-compilation an option here? Is only the combination of Android/ARM supported?

**Comment by Derog-Li** [comment]
@Maratyszcza we have the same problem. we are trying to build NNPack in tegra X1.

**Comment by Maratyszcza** [comment]
It is possible to build NNPACK for/on ARM, but I currently do not provide configuration for such builds. You'd have to patch `configure.py` yourself.

**Comment by dprylipko** [comment]
@Maratyszcza 
Could you maybe suggest whether it is worth to try NNPACK with dual-core ARM processor. I know that NNPACK boosts performance substantially on multi-core CPUs, but what about low-power dual/quad core?

**Comment by Maratyszcza** [comment]
Should be worth it. NNPACK is very efficient in single-threaded mode, but multi-core scaling is actually not great for now.

**Comment by dprylipko** [comment]
I am trying to find the right way to build it for Linux/ARM, but I am afraid my knowledge here is too limited. Trying to make life simpler, I just replaced `gcc` and `g++` in `build.ninja` with `arm-linux-gnueabihf-gcc` and `arm-linux-gnueabihf-g++`, respectively. I also had to introduce some modifications to init.c:

```
diff --git a/src/init.c b/src/init.c
index dac4727..68c2d7b 100644
--- a/src/init.c
+++ b/src/init.c
@@ -207,7 +207,7 @@ static pthread_once_t hwinfo_init_control = PTHREAD_ONCE_INIT;
        }
 #endif

-#if defined(__pnacl__) || defined(__ANDROID__)
+#if defined(__pnacl__) || defined(__ANDROID__) || defined (__arm__)
        static void init_static_hwinfo(void) {
                nnp_hwinfo.cache.l1 = (struct cache_info) {
                        .size = 16 * 1024,
@@ -266,7 +266,7 @@ static pthread_once_t hwinfo_init_control = PTHREAD_ONCE_INIT;
 #endif

 static void init_hwinfo(void) {
-       #if defined(__pnacl__) || defined(__ANDROID__)
+    #if defined(__pnacl__) || defined(__ANDROID__) || defined(__arm__)
                init_static_hwinfo();
        #elif defined(__i386__) || defined(__x86_64__)
                init_x86_hwinfo();
diff --git a/third-party/gtest-1.7.0 b/third-party/gtest-1.7.0
--- a/third-party/gtest-1.7.0
+++ b/third-party/gtest-1.7.0
@@ -1 +1 @@
```

But now I have troubles with benchmarks:

```
/home/dprylipko/Work/playground/NNPACK/bench/perf_counter.c:11:19: fatal error: cpuid.h: No such file or directory
 #include <cpuid.h>
                   ^
compilation terminated.
[91/146] CXX gtest-all.cc
```

Do you maybe have better ideas?

**Comment by Maratyszcza** [comment]
@dprylipko You don't need to compile benchmarks which access CPU cycle counter. These benchmarks are only useful for low-level optimization during NNPACK development.

**Comment by dprylipko** [comment]
Ok, I wiped out benchmarks and managed to compile NNPACK, but linking fails with numerous messages like this:
```
arm-linux-gnueabihf/bin/ld.gold: error: build/x86_64-fma/relu.py.o: incompatible target
```

I am wondering, is it possible to use PeachPy to generate object files for Linux/ARM? If yes, what ABI should I specify? If no, does it mean I cannot build content of the `src/x86_64-fma` ?

**Comment by Maratyszcza** [comment]
Sources in `src/x86_64-fma` are x86-specific. For ARM NNPACK uses a combination of Clang SIMD and ARM NEON intrinsics. See https://github.com/Maratyszcza/NNPACK/blob/master/jni/Android.mk#L18

**Comment by dprylipko** [comment]
Is it mandatory to use clang in this case?

**Comment by Maratyszcza** [comment]
Yes

**Comment by dprylipko** [comment]
Ok, I managed to write a quick and dirty configuration script for Linux/ARM that relies on embtoolkit as the toolchain. Should I integrate it into configure.py and make a pull request, or you want to take care of integrating it?

**Comment by zhengq200618** [comment]
@dprylipko Hi, have you already build NNPACK on ARM success? Now I encounter the same problem.

**Comment by dprylipko** [comment]
@zhengq200618 : I build it not on ARM, but cross-compiled on x86_64 for ARM. Now I want to test it with Caffe, but there are some issues with integration.

**Comment by zhengq200618** [comment]
@dprylipko  Ok, thanks for you reply, Now I'm cross-compiling it on x86 platform for ARM. but I don't know how to change the configure.py and user what command to complie it.

**Comment by dprylipko** [comment]
Here is the script I use:
[configure_linux-arm.py.zip](https://github.com/Maratyszcza/NNPACK/files/654316/configure_linux-arm.py.zip)

Pay attention that you have to build the corresponding toolchain using [embtoolkit](https://www.embtoolkit.org/) first.

**Comment by Maratyszcza** [comment]
@dprylipko As there are other people who want to build NNPACK for ARM, pull request would be useful. I can't promise to integrate it into upstream NNPACK, through.

**Comment by zhengq200618** [comment]
@dprylipko I'm using embtoolkit to build the toolchain ,but I find another error. I don't know why: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~ EmbToolkit ~~ Building new arm-linux/cortex-a7 CORE toolchain - please wait...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~ EmbToolkit ~~ Compile/Install linux-3.4.106 in target system...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
linux using tarball
        Version       : 3.4.106
        From          : http://ftp.kernel.org/pub/linux/kernel/v3.0
        In            : ./dl/linux-3.4.106.tar.xz
        Patched       : No
        Dependency of : N/A
ccache: error: execv of /home/zq/For_tiny/embtoolkit-1.8.0/generated/tools-arm-linux-cortex-a7/bin/arm-unknown-linux-gnueabihf-gcc failed: No such file or directory

**Comment by dprylipko** [comment]
if you have problems with embtoolkit (as I understood), it's better to ask there, I guess. I am also newbie to embtookit and cross-compilation in general.

**Comment by Maratyszcza** [comment]
Now, with the new configuration system (`confu`), NNPACK builds out-of-the-box on ARM. However, as of now, it would use PSIMD kernels rather than ARM NEON kernels.

**Comment by Maratyszcza** [comment]
Now ARM NEON kernels are used by default on ARMv7.

**Comment by andyxxw** [comment]
hi @Maratyszcza,  As you said, NNPACK built on ARM. How to configure the option for a ARM cross compile, like option --target and --toolchain? Thanks
