### ISSUE TITLE
unsupported hardware

### ISSUE THREAD

**Issue by samuel1208** [Maratyszcza/NNPACK#37]
My cpu is `32  Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz`. 
I use **caffe-nnpack** from https://github.com/Maratyszcza/caffe-nnpack.  When I set the `engine to NNPACK`. I found the status return by nnp_intialize() is 51 (/** NNPACK does not implement this function for the host CPU */).

Does my cpu supported nnpack?

**Comment by Maratyszcza** [comment]
No. NNPACK targets Haswell+ CPUs.

**Comment by samuel1208** [comment]
So Are there any way to insert the NNPACK in Xeon CPU

**Comment by Maratyszcza** [comment]
NNPACK works on Xeon CPUs, starting with Xeon v3 series.

**Comment by samuel1208** [comment]
@Maratyszcza  Does it support on  `Intel(R) Core(TM) i7-6700k CPU @ 4.00GHz`

**Comment by Maratyszcza** [comment]
Yes
