### ISSUE TITLE
nnpack in android cost more time in conv than openblas with singlethread.

### ISSUE THREAD

**Issue by conansherry** [Maratyszcza/NNPACK#39]
im2col  + openblas sgemm cost 1/2 time which compared with nnpack in single thread. (multi thread will interference other program in weak cpu of android)
batchsize = 1 using inference mode.
so I continue to use openblas sgemm + im2col.

**Comment by Maratyszcza** [comment]
Which convolution parameters and algorithm do you use?

**Comment by conansherry** [comment]
default param. AUTO BLOCK_BASED

**Comment by conansherry** [comment]
input channels 3
output channels 20
H W = 60 60
stride 2

**Comment by conansherry** [comment]
layer {
    name: "conv1"
    type: "NNPackConvolution"
    bottom: "data"
    top: "conv1"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    convolution_param {
        num_output: 12
        kernel_size: 5
        stride: 2
        weight_filler {
            type: "xavier"
            std: 0.01
        }
        bias_filler {
            type: "constant"
            value: 0.2
        }
    }
}

layer {
    name: "relu1"
    type: "ReLU"
    bottom: "conv1"
    top: "conv1"
}

layer {
    name: "conv2"
    type: "NNPackConvolution"
    bottom: "conv1"
    top: "conv2"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    convolution_param {
        num_output: 20
        kernel_size: 3
        stride: 2
        weight_filler {
            type: "xavier"
            std: 0.1
        }
        bias_filler {
            type: "constant"
            value: 0.2
        }
    }
}

layer {
    name: "relu2"
    type: "ReLU"
    bottom: "conv2"
    top: "conv2"
}

layer {
    name: "conv3"
    type: "NNPackConvolution"
    bottom: "conv2"
    top: "conv3"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    convolution_param {
        num_output: 64
        kernel_size: 3
        stride: 2
        weight_filler {
            type: "xavier"
            std: 0.1
        }
        bias_filler {
            type: "constant"
            value: 0.2
        }
    }
}

layer {
    name: "relu3"
    type: "ReLU"
    bottom: "conv3"
    top: "conv3"
}

layer {
    name: "conv4"
    type: "NNPackConvolution"
    bottom: "conv3"
    top: "conv4"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    convolution_param {
        num_output: 80
        kernel_size: 3
        stride: 2
        pad: 1
        weight_filler {
            type: "xavier"
            std: 0.1
        }
        bias_filler {
            type: "constant"
            value: 0.2
        }
    }
}

layer {
    name: "relu4"
    type: "ReLU"
    bottom: "conv4"
    top: "conv4"
}

**Comment by austingg** [comment]
@conansherry  nnpack only supports conv with 1 stride,  when stride > 1, nnpack also uses im2col + sgemm.
however, I wonder why it cost 2x time compared to openblas.

**Comment by conansherry** [comment]
@austingg new version of nnpack support stride > 1 in reference mode. you can look caffe2. and the new interface of nnpack conv

**Comment by austingg** [comment]
@conansherry  thanks for sharing your experiments result.  I will do some further experiments on openblas with gfortran.

**Comment by conansherry** [comment]
@Maratyszcza  @austingg does the nnpack only support specify size kernel like 3x3 or 16x16?

**Comment by conansherry** [comment]
@Maratyszcza @austingg  oh, i lookup the caff2 implements. i use the tuple_based and everything is ok.

**Comment by conansherry** [comment]
@Maratyszcza @austingg 
Here i will share some result in my experiments.
Android mobile phone. XIAOMI 5 Plus.
dl net contains 4 conv layer and two inner production layer. all conv layer are stride1 and kernel size euqal 5 or 3.
input data N C H W = 1 3 60 60
I run program 10 times for each experiment. here is the results:

openblas with gfortran
time forward 11.841000
time forward 10.097000
time forward 10.139000
time forward 10.583000
time forward 10.498000
time forward 10.358000
time forward 10.501000
time forward 10.440000
time forward 10.524000
time forward 10.268000

NNPACK FFT16X16
time forward 32.105999
time forward 28.781000
time forward 29.034000
time forward 61.912998
time forward 31.129999
time forward 27.649000
time forward 27.438000
time forward 26.731001
time forward 31.448000
time forward 28.899000

NNPACK FFT8X8
time forward 21.823999
time forward 21.607000
time forward 13.321000
time forward 15.339000
time forward 33.285000
time forward 19.327000
time forward 20.174000
time forward 16.476999
time forward 15.926000
time forward 16.066000

NNPACK AUTO
time forward 19.642000
time forward 20.684000
time forward 17.167999
time forward 15.738000
time forward 15.673000
time forward 14.938000
time forward 14.289000
time forward 17.891001
time forward 17.363001
time forward 16.375000

NNPACK SGEMM
time forward 23.778999
time forward 22.764000
time forward 33.705002
time forward 34.299000
time forward 28.004000
time forward 30.851999
time forward 25.034000
time forward 25.563999
time forward 33.702999
time forward 23.247999

**Comment by austingg** [comment]
@conansherry  that's pretty good result for a cnn application only costs about 10 ms on mobile devices. 

According to my research, gfortran is only related to LAPACK, the conv layers only use gemm. Have you ever do some experiments without gfortran, correct me if i am wrong.

**Comment by Maratyszcza** [comment]
1. **implicit GEMM** algorithm is similar to Caffe's im2col+SGEMM, but it is optimized for smaller memory footprint. This memory footprint optimization can make it slower than im2col+SGEMM.
2. For stride > 1 cases only **implicit GEMM** algorithm is supported in NNPACK.
3. When the number of channels on the input to convolution is small, the operation is similar to outer product: it is intrinsically memory bound, and fast algorithms in NNPACK do not help with performance.

**Comment by knsong** [comment]
hi @Maratyszcza, 
 
Are there any tricks to improve the performance of fast algorithms in NNPACK on android devices in the case:

>When the number of channels on the input to convolution is small, the operation is similar to outer product: it is intrinsically memory bound, and fast algorithms in NNPACK do not help with performance.

e.g. tune some parameters such as `nnp_hwinfo.cache`  in NNPACK. 

Thanks in advance.

**Comment by knsong** [comment]
@Maratyszcza  can you give me some hint about: in which cases `nnpack` may have a better performance compared with im2col+gemm using `openblas/eigen` on `armv7` cpu? I also got the similar result as @conansherry 's and I'm wondering why in details fast algorithms in NNPACK appears to be inferior to openblas/eigen.

And how to understand your comment above
>When the number of channels on the input to convolution is small, the operation is similar to outer product: it is intrinsically memory bound, and fast algorithms in NNPACK do not help with performance.

Why would fast algorithms in `NNPACK` be memory bound when the number of channels on the input to convolution is small and thus be inferior to  `openblas/eigen`? I think in this case  im2col+gemm using `openblas/eigen`  will also need to perform a `gemm` operation similar to outer product and be memory bound, but it is faster.

I must have missed something and need to hack into nnpack more thoroughly. Anyway, any little advice will be of great help. Thanks.
