### ISSUE TITLE
build NNPACK error

### ISSUE THREAD

**Issue by tornadomeet** [Maratyszcza/NNPACK#41]
build NNPACK success with https://github.com/Maratyszcza/NNPACK#building after `ninja` every things looks ok.  

but when built with MXNet with NNPACK, it always output these error:
```relocation R_X86_64_32S against `nnp_fft8x8_and_store__avx2' can not be used when making a shared object; recompile with -fPIC```  
so what's this mean? and is this caused by MXNet or NNPACK itself?  

thanks~

**Comment by Maratyszcza** [comment]
NNPACK static library is build as non-PIC, looks like you link it into MXNet dynamic library with PIC. The easiest fix is to build NNPACK as shared library.

**Comment by tornadomeet** [comment]
thanks, fix it!
