### ISSUE TITLE
There are some wrongs with nnp_fully_connected_output

### ISSUE THREAD

**Issue by hfbluehf** [Maratyszcza/NNPACK#44]
hello, @Maratyszcza 
I find there are some wrongs with nnp_fully_connected_output, if batch-size != 4*n.
My config is x86_64-fma, and threadpool is null.

And I find that, at NNPACK-master\src\fully-connected-output.c  Line 40.
If change the 'outer_subblock_max' to 'outer_subblock_size', can fix this problem.

I would like to know whether my amendment is reasonable.
And will it affect efficiency?

**Comment by tornadomeet** [comment]
oh, i found some simillar:  https://github.com/Maratyszcza/NNPACK/issues/43
