### ISSUE TITLE
Does NNPACK support windows?

### ISSUE THREAD

**Issue by tornadomeet** [Maratyszcza/NNPACK#45]
hell,  @Maratyszcza  does NNPACK support windows? as i cannot found in https://github.com/Maratyszcza/NNPACK#host-system .  thanks.

**Comment by knsong** [comment]
As far as I know, it doesn't support windows mainly because of `pthread`. See this thread [#25](https://github.com/Maratyszcza/NNPACK/issues/25).

**Comment by Maratyszcza** [comment]
Windows is currently not supported. See #25 for details.

**Comment by tornadomeet** [comment]
thanks。
