### ISSUE TITLE
Android NDK compile error: complex.h not found

### ISSUE THREAD

**Issue by vpatilvasu** [Maratyszcza/NNPACK#48]
Hi @Maratyszcza 

Compiling NNPACK as it is fails with compilations error: "fatal error: complex.h not found".

My solution: Increasing Android native API level (APP_PLATFORM under jni/Application.mk) to "android-21" resolves this error.

I guess it must be because "complex.h" was introduced in Android-L NDK.

Best Regards,
Vasu

**Comment by knsong** [comment]
This [issue](https://github.com/Maratyszcza/NNPACK/issues/42) may help you.
