### ISSUE TITLE
Error in configure with "pnacl-nacl-newlib" option

### ISSUE THREAD

**Issue by dima-imagry** [Maratyszcza/NNPACK#50]
python ./configure.py --host=pnacl-nacl-newlib
Traceback (most recent call last):
  File "./configure.py", line 865, in <module>
    sys.exit(main())
  File "./configure.py", line 567, in main
    fft_objects = reference_fft_objects + arch_fft_stub_objects
UnboundLocalError: local variable 'arch_fft_stub_objects' referenced before assignment

python --version
Python 2.7.6

**Comment by dima-imagry** [comment]
According to README only host should be changed, however if not options.use_psimd or options.use_scalar or host is "x86_64", variable is undefined

**Comment by Maratyszcza** [comment]
Thanks! Does Imagry use NNPACK? If so, do you mind if I mention it in the README?
