### ISSUE TITLE
Understanding Benchmarks

### ISSUE THREAD

**Issue by gnawice** [Maratyszcza/NNPACK#51]
I'm trying to understand the benchmarks on the main github page.  
1) Are these the timings for a _single_ forward pass through the layer? 
2) Is this leveraging all cores available on the CPU or is this the single core timing? 

I'm asking because I was considering porting NNPack to Windows vs. just using my existing convolution code (I can't easily run NNPack on Windows to estimate the timing myself).  Using the posted benchmarks, it doesn't seem the speed is faster than just an optimized spatial convolution.  

Thanks for any insights.  I appreciated it.

**Comment by Maratyszcza** [comment]
1. Yes, timings are for a single forward pass (with batch size of 64 or 128 depending on the model).
2. Yes, NNPACK was running on all 4 cores/8 threads.

More details are in #9

**Comment by gnawice** [comment]
Thank you. With respect to (1) I was looking at the VGG-A performance.  I was reading the table as saying the second convolution layer took 267 ms (with 16x16 FFT) to process "one" sample. But, are you saying this test is showing the latency of the entire batch of 64 samples undergoing forward predictions?

**Comment by Maratyszcza** [comment]
Yes, timings are per-batch
