### ISSUE TITLE
ninja: error: build.ninja:57: unknown pool name

### ISSUE THREAD

**Issue by janelu9** [Maratyszcza/NNPACK#54]
the last step, it errored again

**Comment by Maratyszcza** [comment]
You need the latest ninja 1.7.2 to build NNPACK

**Comment by janelu9** [comment]
@Maratyszcza How can i install the latest ninja it install 1.3.2 automatically

**Comment by janelu9** [comment]
@Maratyszcza  ok I build one ninja 1.7.2.git by pthon

**Comment by Maratyszcza** [comment]
If you used `install_deps.sh` script, it built Ninja in `~/.local/bin/ninja`

**Comment by janelu9** [comment]
@Maratyszcza  well I find it
