### ISSUE TITLE
configure.py: error: unrecognized arguments: --enable-shared

### ISSUE THREAD

**Issue by janelu9** [Maratyszcza/NNPACK#56]
It errors when I run “ python configure.py --enable-shared” to compile NNPACK. Why ? I just run it as the steps the Mxnet provides:
Now, if the trained model meets some conditions of using NNPACK, you can build MXNet with NNPACK support. here is the steps for you:

    install NNPACK based on this tutorials, that’s to say you need ninja to build NNPACK. make sure add --enable-shared when running configure.py(i.e. python configure.py --enable-shared), because MXNet will link NNPACK dynamically.
    set lib path of NNPACK as the environment variable, such as export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$YOUR_NNPACK_INSTALL_PATH/lib
    add the include file of NNPACK and its third-party to ADD_CFLAGS in config.mk, such as ADD_CFLAGS = -I$(YOUR_NNPACK_INSTALL_PATH)/include -I$(YOUR_NNPACK_INSTALL_PATH)/pthreadpool/include
    set USE_NNPACK = 1 in config.mk.
    build MXNet.

**Comment by Maratyszcza** [comment]
This is a temporary regression due to a change in build systems.

**Comment by janelu9** [comment]
@Maratyszcza  but the mxnet connot be built correctly now

**Comment by Maratyszcza** [comment]
For now, please use commit 9c6747d7b80051b40e6f92d6828e2ed997529cd2, the last before the transition to the new build system.

**Comment by mcxkarakoc** [comment]
Sorry but I couldn't perform to compile NNPACK acc. to [here](https://github.com/Maratyszcza/NNPACK#building). If I switch back to [9c6747d](https://github.com/Maratyszcza/NNPACK/commit/9c6747d7b80051b40e6f92d6828e2ed997529cd2) by `git reset --hard 9c6747d7b80051b40e6f92d6828e2ed997529cd2`, `confu setup` cannot find confu.yaml. If I do not run `confu setup`, `ninja` returns the following error.

`ninja: error: 'NNPACK/third-party/pthreadpool/src/pthreadpool.c', needed by 'NNPACK/third-party/pthreadpool/lib/pthreadpool.c.o', missing and no known rule to make it`

**Comment by Maratyszcza** [comment]
Follow the instructions in the README that you checked out, not the current README

**Comment by mcxkarakoc** [comment]
Finally found the problem, I missed to clone the submodules in the corresponding commit. Now, fixed.

**Comment by tracek** [comment]
Hi - how in the new build system I can get a shared library?

**Comment by Maratyszcza** [comment]
@tracek Its not yet supported. If you just need PIC code, after running `configure.py` edit `build.ninja` and add `-fPIC` to `cflags`.

**Comment by KarlKulator** [comment]
Are there any plans to integrate shared library support? I need it for using the torch ffi-bindings.

**Comment by HaoLiuHust** [comment]
@mcxkarakoc how to clone the submudules in the corresponding commit?

**Comment by edmBernard** [comment]
```
git checkout TO_YOUR_COMMIT
git submodule update --init --recursive
```

**Comment by Maratyszcza** [comment]
No longer relevant due to addition of CMake configs.
