### ISSUE TITLE
Multi-threading problem of NNPACK on ARMv7

### ISSUE THREAD

**Issue by haibara-ai** [Maratyszcza/NNPACK#58]
Hi, @Maratyszcza ,

I ran NNPACK on __armeabi-v7a__ device (__Quad-core__) in inference mode with WINOGRAD algorithm, with threads = __1__, __2__, __4__. The timing are about __135__ ms, __83__ ms and __62__ ms, respectively. It seems that the performance did not speed up as expected when threads increasing. What may be the reason?

Thanks a lot.

**Comment by Maratyszcza** [comment]
A lot of factors could contribute: power caps, memory/cache bandwidth saturation, lot amount of work per core.
