### ISSUE TITLE
ImportError: No module named 'complex_soa' and more compilation errors

### ISSUE THREAD

**Issue by sergboec** [Maratyszcza/NNPACK#59]
Hello @Maratyszcza 
As you recoomend in #56 i have checked out 9c6747d7b80051b40e6f92d6828e2ed997529cd2 revision and trying to build under 64x Ubuntu linux 16.04.
I'm using Python 3.5 in virtual enviroment.
`python ./configure` works fine but ninja is not

> [18/144] PEACHPY[x86-64] x86_64-fma/2d-fft-8x8.py
FAILED: python -m peachpy.x86_64 -mabi=sysv -g4 -mimage-format=elf -I/Documents/src/nnpack/NNPACK/src/x86_64-fma -MMD -MF /Documents/src/nnpack/NNPACK/build/x86_64-fma/2d-fft-8x8.py.o.d -emit-c-header /Documents/src/nnpack/NNPACK/build/x86_64-fma/2d-fft-8x8.py.h -o /Documents/src/nnpack/NNPACK/build/x86_64-fma/2d-fft-8x8.py.o /Documents/src/nnpack/NNPACK/src/x86_64-fma/2d-fft-8x8.py
Traceback (most recent call last):
...
Traceback (most recent call last):
...
File "/Documents/src/nnpack/NNPACK/src/x86_64-fma/fft/real_to_complex_soa_perm.py", line 7, in <module>  import complex_soa
**ImportError: No module named 'complex_soa'**

> [18/144]  PEACHPY[x86-64] x86_64-fma/relu.py
FAILED: python -m peachpy.x86_64 -mabi=sysv -g4 -mimage-format=elf -I/Documents/src/nnpack/NNPACK/src/x86_64-fma -MMD -MF /Documents/src/nnpack/NNPACK/build/x86_64-fma/relu.py.o.d -emit-c-header /Documents/src/nnpack/NNPACK/build/x86_64-fma/relu.py.h -o /Documents/src/nnpack/NNPACK/build/x86_64-fma/relu.py.o /Documents/src/nnpack/NNPACK/src/x86_64-fma/relu.py
Traceback (most recent call last):
...
  File "/Documents/side/python3venvTest/lib/python3.5/site-packages/peachpy/x86_64/operand.py", line 44, in check_operand
    raise TypeError("Unsupported operand: %s" % str(operand))
**TypeError: Unsupported operand: 8.0**

> [18/144] PEACHPY[x86-64] x86_64-fma/max-pooling.py
FAILED: python -m peachpy.x86_64 -mabi=sysv -g4 -mimage-format=elf -I/Documents/src/nnpack/NNPACK/src/x86_64-fma -MMD -MF /Documents/src/nnpack/NNPACK/build/x86_64-fma/max-pooling.py.o.d -emit-c-header /Documents/src/nnpack/NNPACK/build/x86_64-fma/max-pooling.py.h -o /Documents/src/nnpack/NNPACK/build/x86_64-fma/max-pooling.py.o /Documents/src/nnpack/NNPACK/src/x86_64-fma/max-pooling.py
Traceback (most recent call last):
...
  File "/Documents/side/python3venvTest/lib/python3.5/site-packages/peachpy/literal.py", line 56, in encode
    return sum([encode_function(data) for data in self.data], bytearray())
**TypeError: sum() can't sum bytearray [use b''.join(seq) instead]**

**Comment by Maratyszcza** [comment]
Not 100% sure, but looks like Python 3 vs Python 2 problem. I've always built NNPACK with Python 2, so try to edit `build.ninja` and change `python2` variable

**Comment by sergboec** [comment]
Thank you. That helps.
