### ISSUE TITLE
nnp_convolution_inference returns not commented value 

### ISSUE THREAD

**Issue by sergboec** [Maratyszcza/NNPACK#62]
Hello.
Is there any explanation if nnp_status equals to 1 after nnp_convolution_inference function call

**Comment by Maratyszcza** [comment]
Probably a bug. Do the test pass (`ninja smoketest` or `ninja test`)?

**Comment by Maratyszcza** [comment]
From the structure of the source code it seems impossible to return 1 from `nnp_convolution_inference`

**Comment by Maratyszcza** [comment]
@sergboec Have you figured out the problem?

**Comment by sergboec** [comment]
Yes, sorry i forgot. That was wrong stride value, stride was equal to zero
Anyway with correct stride everything ok
