### ISSUE TITLE
Cannot Install confu

### ISSUE THREAD

**Issue by emanueleco** [Maratyszcza/NNPACK#64]
Hi,
when installing confu, I got the following error: 

> CRITICAL:root:failed to detect the host platform: sys.platform = linux2, platform.machine = i686

Actually, platform.machine() gets me 'i686'; in your platform.py script, this possibility is not taken into account. 
I tried to modify the following line in platform.py: 
`x86_64_machines = ["x86_64", "amd64"]`
by adding
`x86_64_machines = ["i686", "x86_64", "amd64"]`

but then NNPACK build fails anyway: the error I get (after the trick above in platform.py) is the following:

> IOError: [Errno 2] No such file or directory: /home/administrator/NNPACK/deps/pthreadpool/configure.py

The reason is that no deps are downloaded when cloning git. 
Any suggestion about?

Thank you. 

Emanuele

**Comment by Maratyszcza** [comment]
Do you have a 64-bit CPU/OS?

**Comment by nopattern** [comment]
Hi @Maratyszcza , thank for your great job. 
   I have met the same problem when I try to build nnpack in  ARM Cortex-A57, which platform is outputed as `'aarch64'.
`Collecting git+https://github.com/Maratyszcza/confu
  Cloning https://github.com/Maratyszcza/confu to /tmp/pip-kzRWXJ-build
    Complete output from command python setup.py egg_info:
    CRITICAL:root:failed to detect the host platform: sys.platform = linux2, platform.machine = aarch64
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-kzRWXJ-build/setup.py", line 3, in <module>
        from confu import __version__, __maintainer__, __email__
      File "confu/__init__.py", line 35, in <module>
        from confu.platform import Platform
      File "confu/platform.py", line 217, in <module>
        host = Platform(detect_host())
      File "confu/platform.py", line 213, in detect_host
        .format(sys=sys, machine=machine))
    ValueError: Unexpected sys.platform, platform.machine combination (linux2, aarch64)
`

**Comment by Maratyszcza** [comment]
@nopattern I suppose your problem is fixed in #71
