### ISSUE TITLE
MIPS support

### ISSUE THREAD

**Issue by sunjunlishi** [Maratyszcza/NNPACK#66]

**Comment by sunjunlishi** [comment]
Does it surpport mips ? can you let it surrport,thanks very much

**Comment by Maratyszcza** [comment]
Its possible to do, but MIPS wouldn't perform well. Baseline MIPS32 ISA doesn't have any SIMD.

**Comment by sunjunlishi** [comment]
if i don't use SIMD, does nnpack has Great benefit to Matrix multiplication

**Comment by Maratyszcza** [comment]
NNPACK does fewer operations than matrix multiplication-based methods, but in absolute performance MIPS would be far slower than ARM and x86.
