### ISSUE TITLE
getting a `nnp_status_unsupported_hardware` with `nnp_initialize()` on OSX 10.11.4

### ISSUE THREAD

**Issue by kashif** [Maratyszcza/NNPACK#7]
Hi,

I am getting a status `nnp_status_unsupported_hardware ` when i call `nnp_initialize()`. Was wondering if you have any idea if I am doing anything stupid?

I am on OSX 10.11.4 

```
$ clang --version            
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Thanks!

**Comment by Maratyszcza** [comment]
Most likely, you are trying to use NNPACK with unsupported processor. NNPACK requires a CPU with AVX2 (Intel Haswell, Broadwell, or Skylake). See [NNPACK Requirements](https://github.com/Maratyszcza/NNPACK#requirements)

**Comment by kashif** [comment]
ah damn you are right... I thought my 2.3 GHz Intel Core i7 was a skylake... ok l will test on another...
