### ISSUE TITLE
--enable-shared not recognized while compiling NNPACK

### ISSUE THREAD

**Issue by piby2** [Maratyszcza/NNPACK#70]
Hello,

I am trying to compile NNPACK to be used with caffe2. I tried the option "--enable-shared", but I got the error message. Can anyone please tell me what to do? I need the shared library from NNPACK, but right now, I only have the static libraries. Thank you.

 python ./configure.py --enable-shared
usage: configure.py [-h] [--target PLATFORM] [--toolchain TOOLCHAIN]
                    [--backend {auto,psimd,scalar}]
configure.py: error: unrecognized arguments: --enable-shared

**Comment by Maratyszcza** [comment]
You don't need to manually build NNPACK, Caffe2 cmake scripts would do that for you.
If you still want to build NNPACK yourself for linking with Caffe2/Caffe/MXNet/etc, edit `build.ninja` (created by `configure.py`) to add `-fPIC` to `cflags` variable.
