### ISSUE TITLE
what's the difference between benchmark's mode?

### ISSUE THREAD

**Issue by silrep2** [Maratyszcza/NNPACK#72]
Hi, everyone
There are four modes in ./benchmark
output, input-gradient, kernel-gradient, inference
What does them means respectively?
When I run "output" "input-gradient" and "kernel-gradient" mode, the result was pretty strange because the first column is always "nan". Only "inference" mode could give Caffe running time. Why would that happen?
Thanks for your help.

**Comment by Maratyszcza** [comment]
The modes choose which NNPACK function is being benchmarked: `nnp_convolution_output`, `nnp_convolution_input_gradient`, `nnp_convolution_kernel_gradient`, and `nnp_convolution_inference`. `nnp_convolution_output` computes layer output (forward propagation), `nnp_convolution_input_gradient` - gradient of layer input (backward propagation), `nnp_convolution_kernel_gradient` - gradient of layer kernel (backward propagation). `nnp_convolution_inference` computes layer output just as `nnp_convolution_output`, but its optimized for batch size 1 (typical for inference), and can use pre-computed kernel transforms. It also currently supports two more algorithms than other modes: implicit GEMM and direct convolution.
