### ISSUE TITLE
Compilation error with caffe2 and tiny-dnn

### ISSUE THREAD

**Issue by kaishijeng** [Maratyszcza/NNPACK#73]
I tried to enable NNPACK with caffe2 and tiny-dnn and see similar errors below on both frameworks.

Below is compilation error with tiny-dnn:

/usr/local/lib/libnnpack.a(convolution-inference.c.o): In function `nnp_convolution_inference':
convolution-inference.c:(.text+0x10d8): undefined reference to `pthreadpool_compute_1d_tiled'
/usr/local/lib/libnnpack.a(convolution-inference.c.o): In function `compute_fast_convolution_inference.isra.6':
convolution-inference.c:(.text.unlikely+0x598): undefined reference to `pthreadpool_compute_2d_tiled'
convolution-inference.c:(.text.unlikely+0x674): undefined reference to `pthreadpool_compute_2d_tiled'
convolution-inference.c:(.text.unlikely+0x7c8): undefined reference to `pthreadpool_compute_2d_tiled'
convolution-inference.c:(.text.unlikely+0x958): undefined reference to `pthreadpool_compute_2d_tiled'
convolution-inference.c:(.text.unlikely+0xa4c): undefined reference to `pthreadpool_compute_2d_tiled'

See belwo for errors with Caffe2:
https://github.com/caffe2/caffe2/issues/459

Do you know potential rootcause of this error?

Thanks,

**Comment by Maratyszcza** [comment]
The problem is caused by not linking `libpthreadpool.a` with NNPACK (pthreadpool is an NNPACK dependency).
cc @Yangqing

**Comment by kaishijeng** [comment]
Why does tiny-dnn have the same issue?

**Comment by Maratyszcza** [comment]
Before NNPACK switched to `confu` configuration system, pthreadpool build objects were included in `libnnpack.a`. Probably tiny-dnn didn't update NNPACK integration after the change.

**Comment by Maratyszcza** [comment]
cc @edgarriba
