### ISSUE TITLE
support used on virtual box 5.1.22 ?

### ISSUE THREAD

**Issue by gqjjqg** [Maratyszcza/NNPACK#76]
host cpu: I5-4460 
virtual os: ubuntu-16.x64 
cat /proc/cpuinfo:
flags  : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm avx2

run NNPACK, it's return not support CPU instruction set.

**Comment by Maratyszcza** [comment]
NNPACK detects that CPU supports AVX2 and OS/environment preserves YMM registers during context switch. It looks like VirtualBox doesn't do the latter (or doesn't indicate it to user-mode programs).
