### ISSUE TITLE
NNPACK on Intel Haswell

### ISSUE THREAD

**Issue by edmBernard** [Maratyszcza/NNPACK#79]
Have you test NNPACK on Intel Haswell ?
I got this error when I run test : 
```
[0/7] RUN convolution-output-smoketest
convolution-output-smoketest: /home/ubuntu/NNPACK/test/convolution-output/smoke.cc:303: int main(int, char**): Assertion `init_status == nnp_status_success' failed.
Aborted (core dumped)
FAILED: convolution-output-smoketest 
/home/ubuntu/NNPACK/bin/convolution-output-smoketest 
ninja: build stopped: subcommand failed.
```
I don't know if it's due to Intel Haswell or something else.

**Comment by edmBernard** [comment]
That crash don't come from haswell. 
I'll search a bit more to find more clue to find origin.

**Comment by truedat101** [comment]
Getting the same error on a GCP VM which I did confirm is a haswell CPU.  A few more details:

- debian 9
- multi-core system, confirmed haswell generation CPU
- using clang
- in build.ninja, I have modified the optflags to include additional optimizations

**Comment by edmBernard** [comment]
I close my issue because the error don't come from Haswell architecture but from virtual device : 
https://github.com/Maratyszcza/NNPACK/issues/81
Error was due to missing L3 cache on my OVH VM.

**Comment by truedat101** [comment]
@edmBernard thank you - good explanation.  Curious, I'm seeing this problem on GCP if I enable psimd backend.  I feel, at least from reviewing the cpu information, that per-requisites are met.

**Comment by edmBernard** [comment]
The missing L3 cache can be seen if you execute `cache-info` from https://github.com/Maratyszcza/cpuinfo
