### ISSUE TITLE
implicit declaration of function 'psimd_concat_lo_f32'

### ISSUE THREAD

**Issue by zfc929** [Maratyszcza/NNPACK#80]
jni/../src/psimd/fft/soa.h:59:2: warning: implicit declaration of function 'psimd_concat_lo_f32' [-Wimplicit-function-declaration]
  psimd_f32 w0145r = psimd_concat_lo_f32(w0123r, w4567r);

**Comment by Maratyszcza** [comment]
I think you have out-of-date dependencies. To update run `rm -rf deps && confu setup`

**Comment by zfc929** [comment]
thanks

在 2017-05-19 13:28:12，"Marat Dukhan" <notifications@github.com> 写道：


I think you have out-of-date dependencies. To update run rm -rf deps && confu setup
