### ISSUE TITLE
Ubuntu Installation Error

### ISSUE THREAD

**Issue by jsuit** [Maratyszcza/NNPACK#83]
The instructions for building NNPACK are wrong on the README file. The ninja version is 1.5 that Ubuntu's package manager is installed, and NNPACK says it requires 1.7. 

Specific error is "ninja: fatal: ninja version (1.5.1) incompatible with build file ninja_required_version version (1.7)."

**Comment by Maratyszcza** [comment]
If you distributive doesn't provide Ninja 1.7, please build a recent Ninja version [from sources](https://ninja-build.org/)

**Comment by xiaomage11** [comment]
@jsuit please tell me how to do for this error,thanks
