### ISSUE TITLE
cmake support

### ISSUE THREAD

**Issue by edgarriba** [Maratyszcza/NNPACK#88]
Any plan to support cmake build setup?

**Comment by Maratyszcza** [comment]
Yes, but limited to mobile platforms for now. We are going to merge [Caffe 2 CMake files for NNPACK](https://github.com/caffe2/caffe2/blob/master/cmake/External/nnpack.cmake) into NNPACK itself.

**Comment by edgarriba** [comment]
cool, better than nothing

**Comment by Maratyszcza** [comment]
CMake configuration files for mobile have landed. Build example:
```bash
mkdir build
cd build
cmake ..
    -G Ninja
    -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake
    -DANDROID_STL=c++_static
    -DCMAKE_ANDROID_STL_TYPE=c++_static
    -DANDROID_ABI=arm64-v8a
ninja
```

**Comment by Maratyszcza** [comment]
Supported everywhere with dd0e4637190734536cd947cd45bf09b2af68e26d
