### ISSUE TITLE
8-bit inference Tensorflow

### ISSUE THREAD

**Issue by atrah22** [Maratyszcza/NNPACK#91]
Hello,
I was wondering about these below questions.

1) Recently tensorflow provides 8-bit inference option and it seems to be suitable for embedded devices. Also 8-bit inference (8-bit mul & 32 bit accumulation) using low level function gemmlowp used by Tensorflow (optimized heavily for ARM SIMD NEON) shows superior performance. Is there any future plan to develope low-level function using wingorad algorithm for 8-bit computation precision?

2) Will winograd algorithm have benefits (performance) over im2col+GEMM in case of 8-bit computation precision? What will be the impact on accuracy?

**Comment by Maratyszcza** [comment]
No plans for 8-bit inference.
