### ISSUE TITLE
buid error--pthreadpool.h cannot find for caffe2

### ISSUE THREAD

**Issue by zebrajack** [Maratyszcza/NNPACK#95]
I don't know if it right place to ask this question.

![image](https://user-images.githubusercontent.com/1118889/29407103-cfd15c7a-8375-11e7-9260-cdee6327e824.png)
looks like old questions, but are there any better method to solve this problem.
https://github.com/caffe2/caffe2/issues/982

**Comment by edmBernard** [comment]
when you install nnpack from source, there is the  `confu setup ` command to run. It will download [pthreadtool](https://github.com/Maratyszcza/pthreadpool) in a `third-party` folder
