### ISSUE TITLE
Pre-allocated workspace buffers in nnp_convolution_inference()

### ISSUE THREAD

**Issue by sby** [Maratyszcza/NNPACK#96]
I found that _convolution-benchmark_ doesn't work when using the _direct_ algorithm.

For example:
$ convolution-benchmark -ic 3 -oc 64 -is 224 224 -ks 1 1 -i 10 -m inference -a direct

This is because _nnp_convolution_algorithm_direct_ requires no workspace.

When using pre-allocated workspace buffers, _nnp_convolution_inference_ will be invoked twice:
 
1.  workspace_buffer is NULL and workspace_size is non-NULL,
NNPACK stores 0 to workspace_size and exits without computations.

since the workspace_size is 0, _convolution-benchmark_ would not allocate memory for workspace_buffer.

2. workspace_buffer is still NULL and workspace_size is non-NULL.
_nnp_convolution_inference_ would still return without any computation.

The followings are two possible workarounds:

```diff
diff --git a/bench/convolution.c b/bench/convolution.c
index 8887eb3..ba07e83 100644
--- a/bench/convolution.c
+++ b/bench/convolution.c
@@ -147,7 +147,7 @@ struct nnp_profile benchmark_convolution(
                                        algorithm, transform_strategy,
                                        input_channels, output_channels,
                                        input_size, input_padding, kernel_size, output_subsampling,
-                                       input, kernel, bias, output, memory_block, &memory_size,
+                                       input, kernel, bias, output, memory_block, (memory_size == 0) ? NULL : &memory_size,
                                        nnp_activation_identity, NULL,
                                        threadpool,
                                        &computation_profile[iteration]);

OR

diff --git a/src/convolution-inference.c b/src/convolution-inference.c
index b0e51b3..e5045a1 100644
--- a/src/convolution-inference.c
+++ b/src/convolution-inference.c
@@ -906,7 +906,7 @@ static enum nnp_status compute_direct_convolution_inference(
        const size_t image_elements = image_size.height * image_size.width;

        if (workspace_buffer == NULL && workspace_size != NULL) {
-               *workspace_size = 0;
+               *workspace_size = 1;
                return nnp_status_success;
        }

**Comment by Maratyszcza** [comment]
Thank you for reporting and investigating the issue. The bug is fixed in 12f721492adade7f235249afb53800c4d5f66704
