### ISSUE TITLE
please tell me where is the lib？

### ISSUE THREAD

**Issue by xiaomage11** [Maratyszcza/NNPACK#97]
I look at your readme. it tell me :Binary packages need to distribute two files: include/nnpack.h and lib/libnnpack.a (also lib/libnnpack.so or lib/libnnpack.dylib if NNPACK was configured with shared library support). but I could not find lib/libnnpack.a.please tell me where is it.thanks! @Maratyszcza

**Comment by edmBernard** [comment]
in NNPACK/lib folder

**Comment by Maratyszcza** [comment]
@xiaomage11 You need to build NNPACK (follow instructions in the README), then you'll find the library in `$NNPACK_ROOT/lib/libnnpack.a`. If you build for Android with `ndk-build`, the libraries will be in `$NNPACK_ROOT/libs/<abi>/libnnpack.a`.

**Comment by xiaomage11** [comment]
@Maratyszcza  I build NNPACK follow the instructions,but I could not find the lib in NNPACK,where is the NNPACK_ROOT ,is it in the usr/lib ?

**Comment by xiaomage11** [comment]
@edmBernard  I do not have have the lib folder in NNPACK

**Comment by edmBernard** [comment]
@xiaomage11 NNPACK_ROOT is the folder where you have nnpack source code
when you build source the lib folder will be created with all lib in it.
Are you sure you follow the [build process](https://github.com/Maratyszcza/NNPACK#building) and got no error ?
