### ISSUE TITLE
run the last step is error

### ISSUE THREAD

**Issue by xiaomage11** [Maratyszcza/NNPACK#98]
@Maratyszcza I build NNPACK and run the last step：ninja system show the error : ninja: fatal: ninja version (1.5.1) incompatible with build file ninja_required_version version (1.7).  I want ask how to do for the error. thank you!

**Comment by edmBernard** [comment]
@xiaomage11 
to install last ninja version : 
* download binary from 
https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
* or build from source
`git clone git://github.com/ninja-build/ninja.git && cd ninja && ./configure.py --bootstrap`
