### ISSUE TITLE
Can I integrate NNPACK to another version of caffe namely https://github.com/xingwangsfu/caffe-yolo

### ISSUE THREAD

**Issue by ashwinnair14** [Maratyszcza/NNPACK#99]
Is there a way I can integrate NNPACK to another version of caffe in a straight forward manner ?
Can I just copy the files that different like the FindNNpack.cmake and the NNpack_convolution_layer etc.

Or do I also have to change other files internally to support NNPACK ??
@Maratyszcza

**Comment by Maratyszcza** [comment]
If you reapply my commits from **caffe-nnpack** repo, it will probably "just work". Keep in mind that **caffe-nnpack** is not actively maintained, so you'd have to debug the arising problem yourself.
